# Generated by Django 4.2.28 on 2026-03-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatusType',
            fields=[
                ('typeId', models.IntegerField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=222)),
            ],
            options={
                'ordering': ['-typeId'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('url', models.CharField(max_length=1000, null=True)),
                ('Phone', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=255)),
                ('InstituteId', models.IntegerField()),
                ('BranchId', models.IntegerField(null=True)),
                ('userTypeId', models.IntegerField()),
                ('IsActive', models.BooleanField()),
            ],
            options={
                'db_table': 'Users',
                'ordering': ['-userId'],
            },
        ),
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('StatusId', models.IntegerField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('IsActive', models.BooleanField(default=True)),
                ('StatusTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIWGS.datastatustype')),
            ],
            options={
                'ordering': ['-StatusId'],
            },
        ),
    ]
