# Generated by Django 4.2.28 on 2026-03-22 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataStatusType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=222)),
            ],
            options={
                'db_table': 'DataStatusType',
                'ordering': ['-typeId'],
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('InstituteId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField()),
                ('Url', models.ImageField(null=True, upload_to='InstituteImage/')),
                ('Created_At', models.DateTimeField()),
                ('Address', models.CharField()),
                ('IsActive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Institute',
                'ordering': ['-InstituteId'],
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('moduleId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Code', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Modules',
                'ordering': ['-moduleId'],
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('permissionId', models.AutoField(primary_key=True, serialize=False)),
                ('codeName', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=500)),
                ('httpMethod', models.CharField(max_length=1000)),
                ('urlPatter', models.CharField(null=True)),
                ('IsActive', models.BooleanField(default=False)),
                ('modeuleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIWGS.modules')),
            ],
            options={
                'db_table': 'Permissions',
                'ordering': ['-permissionId'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('Role_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=1000)),
                ('IsActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Roles',
                'ordering': ['-Role_Id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('Age', models.IntegerField()),
                ('url', models.ImageField(null=True, upload_to='userImages/')),
                ('Phone', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=255)),
                ('BranchId', models.IntegerField(null=True)),
                ('userTypeId', models.IntegerField()),
                ('IsActive', models.BooleanField()),
                ('Created_At', models.DateTimeField(null=True)),
                ('InstituteId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AIWGS.institute')),
            ],
            options={
                'db_table': 'Users',
                'ordering': ['-userId'],
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('userRoleId', models.AutoField(primary_key=True, serialize=False)),
                ('AssignedAt', models.DateTimeField()),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIWGS.roles')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIWGS.users')),
            ],
            options={
                'db_table': 'UserRoles',
                'ordering': ['-userRoleId'],
            },
        ),
        migrations.CreateModel(
            name='RolesPermissions',
            fields=[
                ('rolePermissionId', models.AutoField(primary_key=True, serialize=False)),
                ('grantedAt', models.DateTimeField()),
                ('PermissionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIWGS.permissions')),
                ('roleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIWGS.roles')),
            ],
            options={
                'db_table': 'RolePermissions',
                'ordering': ['-rolePermissionId'],
            },
        ),
        migrations.CreateModel(
            name='DataStatus',
            fields=[
                ('StatusId', models.AutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField()),
                ('IsActive', models.BooleanField(default=True)),
                ('InstituteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIWGS.institute')),
                ('StatusTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AIWGS.datastatustype')),
            ],
            options={
                'db_table': 'DataStatus',
                'ordering': ['-StatusId'],
            },
        ),
    ]
